### ISSUE TITLE
Setup PWA

### ISSUE THREAD

**Issue by Alex-Ri** [Alex-Ri/coffee-larries#13]
**Dod:** 
- manifest 
- meta viewport 

`<meta name="apple-mobile-web-app-capable" content="yes">
		<meta name="apple-mobile-web-app-status-bar-style" content="white-transculent">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">`

**Comment by eybarra10** [comment]
Finished 👍
